// Dice Rolling
#include <iostream>
#include <iomanip>
#include <ctime>        // for seeding the PRNG
#include <cstdlib>      // for PRNG

using namespace std;

#define TIMES_TO_ROLL 36000 // number of times dice must be rolled
#define SUM_ARRAY_SIZE 13 // will only use indices 2-12

int main(void){

    // seed the Pseudo-Random Number Generator
    srand(time(NULL));

    unsigned short die1 = 0, die2 = 0;  // the two dice rolled

    unsigned short diceSums[SUM_ARRAY_SIZE] = {};    // array to hold the dice sums

    for (int roll = 0; roll < TIMES_TO_ROLL; roll++){
        // roll both dice
        die1 = 1 + rand() % 6;
        die2 = 1 + rand() % 6;

        // tally the sum count in the array
        diceSums[die1+die2]++; 
    }

    // print the results, skipping first 2 indices
    cout << "Following results were generated by 36,000 dice rolls" << endl;
    cout << setw(5) << left << "Sum" << setw(10) << "Occurances" << endl;

    for (int i=2; i<SUM_ARRAY_SIZE; i++){
        cout << setw(5) << left << i << setw(10) << diceSums[i] << endl;
    }

    return 0;
}
